name: Check Action

on:
  workflow_dispatch:

jobs:
  run:
    name: Run Action
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: action-step
        with:
          path: ./test/
      - run: 'echo MSRV is ${{ steps.action-step.outputs.msrv }}'
